### ISSUE TITLE
Share an example app

### ISSUE THREAD

**Issue by supportreq** [Credntia/CVScanner#14]
Please share an example app, I am unable to compile the code and also unable to use it as required..

 E/OpenCameraSource: Exception thrown from receiver.
                                                                                   CvException [org.opencv.core.CvException: cv::Exception: /Volumes/Linux/builds/master_pack-android/opencv/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function void cv::resize(cv::InputArray, cv::OutputArray, cv::Size, double, double, int)
                                                                                   ]
                                                                                       at org.opencv.imgproc.Imgproc.resize_1(Native Method)
                                                                                       at org.opencv.imgproc.Imgproc.resize(Imgproc.java:2716)
                                                                                       at devliving.online.cvscanner.util.CVProcessor.getQuadForPassport(CVProcessor.java:321)
                                                                                       at devliving.online.cvscanner.PassportDetector.detectDocument(PassportDetector.java:106)
                                                                                       at devliving.online.cvscanner.PassportDetector.detect(PassportDetector.java:42)
                                                                                       at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:31)
                                                                                       at online.devliving.mobilevisionpipeline.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1247)
                                                                                       at java.lang.Thread.run(Thread.java:764)

**Comment by iamMehedi** [comment]
A sample app is already there in this repo.
